### ISSUE TITLE
OSM and Sonata Load Experiment

### ISSUE THREAD

**Issue by ashwinprasadme** [CN-UPB/pg-scrambLe#66]
## @bhargavimohan  Tasks:

- [x]  VM Config and Ubuntu setup

- [x]  Install tools
  - [x] OSM
  - [x] netdata
  - [x] openstack 

- [x] Decide NSD/VNFD
  - [x] Have multiple options (2-3)
  - [x] Establish baseline experiment (dummy nsd/vnfd?)

- [x] Decide experiment data structure
  - [x] what to collect?
  - [x] how much/long to collect? (time?)
  - [x] charts?
  - [x] Questions to be answered by the test data?
  - [x] How to store and how to present results?

- [x] Start experiment
  - [x] collect data as planned
  - [x] document results

- [x] Repeat experiment with different NSD/VNFD
  - [x] Also vary other parameters (# instances?)
  - [x] Try inducing some load on the running VNF

- [ ] ....

---

## @dramesh94  Tasks:

- [x]  VM Config and Ubuntu setup

- [x]  Install tools
  - [x] Pishahang
  - [x] netdata
  - [x] openstack 

- [x] Decide NSD/VNFD
  - [x] Have multiple options (2-3)
  - [x] Establish baseline experiment (dummy nsd/vnfd?)

- [x] Decide experiment data structure
  - [x] what to collect?
  - [x] how much/long to collect? (time?)
  - [x] charts?
  - [ ] Questions to be answered by the test data?
  - [ ] How to store and how to present results?

- [ ] Start experiment
  - [ ] collect data as planned
  - [ ] document results

- [ ] Repeat experiment with different NSD/VNFD
  - [ ] Also vary other parameters (# instances?)
  - [ ] Try inducing some load on the running VNF

- [ ] ....

**Comment by bhargavimohan** [comment]
Tools set up and initial data analysis has been completed. Next up is to carry out the experiment with different NSDs/VNFDs and record the results.

**Comment by iashwinprasada** [comment]
+ Progress on NS instantiation and initial experiment runner for OSM
+ Working on Pishahang and updates to follow in the next week
+ Working on automated storage of experiment results into csv
