### ISSUE TITLE
son-gui and gatekeeper changes for adding MANO references

### ISSUE THREAD

**Issue by ashwinprasadme** [CN-UPB/pg-scrambLe#70]

**Comment by iashwinprasada** [comment]
+ Progress on setting up docker environment
+ All the required changes made to ruby, sintara and others
+ Working on debugging and workflow

**Comment by iashwinprasada** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by iashwinprasada** [comment]
The task list as discussed to take this forward

- [ ] Fix the docker run and debug environment for testing gtkapi
- [ ] Add a simple GET request to gtkapi and test if it is working 
- [ ] Decide the MANO instances schema and decide where to store the tables
- [ ] Make a copy of existing VIM handler code and use it as an example for adding MANO instances
- [ ] Add a POST request handler to gtkapi to receive new MANO instances(if needed add a separate docker for this)
- [ ] Add a GET request to receive added MANO instances from the stored database
- [ ] Make modifications to the frontend to make REST calls to the new calls and test adding and listing
- [ ] Publish gtkapi docker image to own docker hub repository
- [ ] Make changes to ansible installation to automatically install published gtkapi docker image
