### ISSUE TITLE
Final scenario for demo

### ISSUE THREAD

**Issue by ashwinprasadme** [CN-UPB/pg-scrambLe#85]
- [x] Figure out how to get floating-ip in OSM NSD
- [ ] How to hardcode IP-Address in pishahang NSD?
- [ ] Can we do cloud-init in pishahang?
    + If not possible, how to do dynamic configuration? (Installing packages, writing files)
        + SSM? but how? examples..

Reference NSD: 
- OSM
https://github.com/ashwinprasadme/Future-Internet-SS19-Mini-Project/blob/master/Descriptors/Loadbalancing-NS/OSM-Descriptors/scramble_3vnf_load_balancer_nsd/scramble_3vnf_load_balancer_nsd.yaml

- Use this for dev
   - https://github.com/CN-UPB/pg-scrambLe/blob/54231f064baa22195180c5d95a7f6edec4dc96e2/experiments/experiment-runner/OSM/Descriptors/cirros_ns/cirros_vnf_vnfd.tar.gz

   - https://github.com/CN-UPB/pg-scrambLe/blob/54231f064baa22195180c5d95a7f6edec4dc96e2/experiments/experiment-runner/OSM/Descriptors/cirros_ns/cirros_case1_nsd.tar.gz

- Pishahang
https://github.com/CN-UPB/pg-scrambLe/blob/master/src/translator/descriptors_examples/NSD.yaml#L48

**Comment by suheelsn** [comment]
Getting floating IP for VNF instance in OSM.
- Set config parameter 'use_floating_ip' for vim either by command line --config='{use_floating_ip: True} or through GUI while adding the VIM. (this is specific to openstack vim).
   - https://osm.etsi.org/wikipub/index.php/Openstack_configuration_(Release_THREE)
- Make sure connection-point details are added to the NSD.
- Make sure the network used in the descriptor is connected to public network through interface.
